language: node_js
node_js:
  - '12'

cache:
  directories:
    - '.eslintcache'
    - 'node_modules'

script:
  - npm run build
  - npm run lint
  - npm run test:ci

notifications:
  email: false

branches:
  only: master
